### ISSUE TITLE
Mkreadme script - namelists structuring in Version 4 issue

### ISSUE THREAD

**Issue by lmicallef** [immerse-project/nemo-simsar#1]
The current mkreadme script can be executed from a Nemo v3 and Nemo v4. However, the section reflecting the namelist_cfg has different parameters between the two version e.g. in Release 3 (and these do not correspond to the namelists in Release 4): 

namcfg | jp_cfg
namcfg | cp_cfg
namzgr | .true. (zco, zps, sco, isfcav)
namcfg | jpidta \| ﻿jpjdta
namcfg | jpkdta
namsbc | ln_ \| true \| ana, flux, blk_clio etc..

**Comment by mscheinert** [comment]
This has been solved since commit fb513a9468f6066fceb0679d1d95a57a0bb2ff02.
I've used the **netCDF4** module (as "nc") and used the `nc.Dataset()` call to create a new data set objkect. The contents of the NetCDF variable can then be retrieved by `ds['PARAMETERNAME'][:]`

**For example:**

https://github.com/immerse-project/nemo-simsar/blob/fb513a9468f6066fceb0679d1d95a57a0bb2ff02/src/mkReadme.py#L897-L915

I'm closing this issue since this is solved and implemented.
